bafs/templates/leaderboard/indiv_various.html, bafs/views/chartdata.py
These rank individual athletes based on coldest ride, ride
with most rain, and ride with most snow.  They show up as
new options under Leaderboards -> Individual (various).
=> Add options for Coldest, Raniest, Snowiest to idiv_various

freezing/web/templates/pointless/coffeeride.html, freezing/web/views/pointless.py
=> Fix up 2019 Coffee Ride hashtag

example.cfg, freezing/web/config.py, freezing/web/data.py, freezing/web/templates/login_results.html, freezing/web/views/general.py, setup.py
Release 1.1.0
Should fix login for people who are only on the main team,
as is the case in the early days of the competiton.
=> Fix login to ball back to main team. rel 1.1.0

freezing/web/templates/base.html, freezing/web/templates/pointless/coffeeride.html, freezing/web/templates/pointless/pointlesskids.html, freezing/web/views/pointless.py
- Added pointless kid leaderboard
- update coffee ride leaderboard to read year automatically
=> Pointless kid leaderboard, automatic year updating for coffee ride

requirements.txt
Also clean up requirements.txt to specify versions
and sort it
=> Fix CVE-2017-18342 (update PyYAML)

LICENSE
One of the setup files specified Apache license, let's make it explicit
=> Apply Apache 2.0 license

freezing/web/templates/base.html
=> Fix Navbar collapse

freezing/web/templates/base.html, freezing/web/templates/leaderboard/team_text.html, freezing/web/views/chartdata.py, freezing/web/views/leaderboard.py, freezing/web/views/shared_sql.py, requirements.txt
=> Implement Team Stats 100 mile limit (Fixes #65)

freezing/web/views/pointless.py, leaderboards/avgdist.yml, leaderboards/avgspeed.yml, setup.py
=> Fix points-per-mile ride days

freezing/web/templates/base.html, freezing/web/templates/pointless/kidsathlon.html, freezing/web/views/people.py, freezing/web/views/pointless.py
=> add kidsathlon prize

freezing/web/views/pointless.py
I hate math. I have no idea why I was a math major. Initial patch wasn't doing the math correctly - mixture of ints and floats and whatnot. So I explicitly made everything a float and it seems fine now
=> fix stupid float math

freezing/web/templates/people/show.html
=> Add link to Strava profile on show person page

freezing/web/views/people.py, setup.py
Python time zones are tricky!
* Fixes #77
* Fixes #68
* Fixes #34
=> Really REALLY fix ride days leaderboard

freezing/web/views/chartdata.py, freezing/web/views/people.py, setup.py
See https://stackoverflow.com/a/25265611/424301
Add Stack Overflow credits inline
=> Use pytz.utc to fix up local time zones in reports

freezing/web/config.py, freezing/web/views/people.py, setup.py
=> Fix issues with people pages

freezing/web/views/pointless.py
=> don't double count miles

freezing/web/templates/alt_scoring/indiv_worst_day_points.html, freezing/web/views/alt_scoring.py
It was 200 last year for 250 total riders - we have 180 or something now
=> adjust median number of daily riders

leaderboards/opmdays.yml
We have a second official OPM snow day to add to Kitty's leaderboard
=> add 2/20 to snow day prize

CODE_OF_CONDUCT.md
Use the Contributor Covenant from the GitHub templates
=> Create code of conduct file

freezing/web/templates/leaderboard/team_various.html, freezing/web/views/shared_sql.py
Sleaze day calculations are now based on miles rather than points.
=> Declining points

freezing/web/templates/leaderboard/team_text.html, freezing/web/views/chartdata.py, freezing/web/views/leaderboard.py, freezing/web/views/shared_sql.py
This updates the team and individual leaderboard to remove the points cap and all textual references to it. The remaining task is to fix the team points chart.
=> Remove team points cap

freezing/web/templates/leaderboard/indiv.html, freezing/web/templates/leaderboard/team.html
=> adapt chart sizes to row count, fix font sizes, async data load

freezing/web/templates/alt_scoring/indiv_worst_day_points.html, freezing/web/views/alt_scoring.py
=> compute mean number of riders on the fly

freezing/web/static/css/styles.css, freezing/web/templates/base.html, freezing/web/templates/pointless/generic.html, freezing/web/utils/genericboard.py, freezing/web/views/pointless.py, leaderboards/alexandria.yml, leaderboards/dumpling.yml, leaderboards/londonbridge.yml, leaderboards/lostdog.yml, leaderboards/poggio-indiv.yml, leaderboards/poggio-team.yml, leaderboards/tandem.yml, requirements.txt
=> POGGIO and Alexandria Infrastructure leaderboards

requirements.txt
This resolves https://github.com/freezingsaddles/freezing-model/issues/20
=> Fix daily scores again, 10 mile rides got 10 extra

requirements.txt
=> Fix marshmallow upgrade

leaderboards/poggio-indiv.yml, leaderboards/poggio-team.yml
=> update poggio urls

freezing/web/templates/base.html, freezing/web/views/pointless.py, leaderboards/arlington-ccw.yml, leaderboards/arlington-cw.yml, leaderboards/arlington.yml
Extract multisegment leaderboards, build combined arlington loop leaderboard. Closes #119.
=> loopy for arlington leaderboardata

freezing/web/templates/base.html, freezing/web/templates/pointless/hashtag.html, freezing/web/utils/hashboard.py, freezing/web/views/pointless.py, leaderboards/avgdist.yml, leaderboards/avgspeed.yml, leaderboards/dirtybiker.yml, leaderboards/dumpling.yml, leaderboards/hashtag.yml, leaderboards/londonbridge.yml, leaderboards/lostdog.yml, leaderboards/opmdays.yml, leaderboards/tandem.yml
Doughnut, taco and deflated rides. Closes #50, closes #149, closes #150.
=> put together some generic hashtag leaderboards

leaderboards/dirtybiker.yml
=> Dirty, dirty #dirtybiker hashtags

freezing/web/templates/pointless/pointlesskids.html
Just changing the text on the leaderboard page
=> Update Pointless Kids leaderboard explanation

freezing/web/templates/base.html, leaderboards/dirtybiker.yml, leaderboards/suppleride.yml
While the mere thought of a 4" tyre fills me existential dread, this hypothetically closes #132.
=> real supple ride

freezing/web/templates/base.html, freezing/web/templates/index.html
Commented out the HTML elements on the base and index to address #170 and should be easy to re-enable once Dark Sky is working.
Resolves #170
=> Hide weather

leaderboards/opmdays.yml
=> Michigan Day is Jan 26, 2020

freezing/web/templates/pointless/kidsathlon.html
Perks of contributing to the website are tweaking things for your own personal gain or satisfaction. I won this award previously and do not need to repeat as champion, even if I'm at the top of the leaderboard
=> Update text on kidsathlon leaderboard

Dockerfile, freezing/web/templates/base.html, freezing/web/templates/pointless/hashtag.html, freezing/web/utils/hashboard.py, freezing/web/views/pointless.py, leaderboards/hashtag.yml
Add hashboard, some cleanup. Closes #171.
=> chocolateuring hashtag and cleanup

freezing/web/views/chartdata.py
Current weekly team points are somewhat random. Team 12 isn't all that great. Closes #185.
=> fix weekly stats to be a bit more orderly

freezing/web/views/chartdata.py
=> round, don't floor, chart data

requirements.txt, setup.py
Docker Hub had a [failing docker build](https://hub.docker.com/repository/registry-1.docker.io/freezingsaddles/freezing-web/builds/3b84dc71-e91b-4e7e-af3f-3eb41b40d5b8), this should fix it.
=> Try to fix docker build with new freezing-model

freezing/web/templates/base.html, leaderboards/hashtag.yml, leaderboards/rosshillloop.yml, requirements.txt
=> Easily updated pointless prizes for 2023

.github/workflows/build-latest.yml, .github/workflows/build-tag.yml, .github/workflows/build.yml
fixes #250  more authoritatively
=> Sequence build and deploy better

.github/workflows/build-docker.yml, .github/workflows/build-latest.yml, .github/workflows/build-tag.yml, .github/workflows/build.yml
Do not push to docker registry if Dependabot is running the action
=> Dependabot happiness fixes

requirements.txt
=> Fix up PyMySQL

freezing/web/templates/explore/distance_by_lowtemp.html
=> Replace highcharts with c3js

freezing/web/static/css/styles.css, freezing/web/templates/base.html
=> Make the footer less ill-aligned

README.md, freezing/sql/generate-table-counts-query.sql, freezing/sql/table-counts-before-table-drop.sql, freezing/sql/table-counts.sql, freezing/sql/year-start.sql
Resolves #273  (along with actually doing the edits to `.env` and the database, of course)
=> 2025 season site reset docs improvement

example.cfg, freezing/web/__init__.py, freezing/web/config.py, freezing/web/templates/authorization_success.html, freezing/web/views/general.py
=> fix confusing login message

freezing/web/templates/authorize.html, freezing/web/templates/base.html
=> Restore register link

Dockerfile, alembic.ini, freezing/web/data.py, freezing/web/version.py, requirements.txt, setup.py
- Database library upgrade, including SQLAlchemy 1.4 and GeoAlchemy2
- Fix logging and version bugs on startup
- Maybe get Alembic config file working
Resolves #295 
Resolves https://github.com/freezingsaddles/freezing-sync/issues/56
=> upgrade database libraries

freezing/web/views/api.py
apply advice from https://www.educba.com/flask-jsonify/
=> jsonify output

freezing/web/static/css/styles.css, freezing/web/static/js/ride-map.js, freezing/web/templates/base.html, freezing/web/templates/index.html, freezing/web/templates/pointless/hashtag.html, freezing/web/templates/user/rides.html, freezing/web/views/api.py, leaderboards/hashtag.yml
The my rides page was broken by bootstrap 5. Also it should include a ride map. This is stacked on polyline heatmap.
This also adds ride maps to hash tag pages.
=> Fix my rides page and some other stuff

freezing/web/templates/base.html, requirements-test.txt
**Put pointless prefix items back in pointless menu**
I forgot to add this to the last PR.
See #336   
See #303
=> pointless menu reshuffle

freezing/web/templates/base.html, leaderboards/hashtag.yml
=> Add singlespeed to sponsored

freezing/web/templates/base.html
Page left nested in a `<li>` tag.
=> fix html shame

freezing/web/templates/explore/distance_by_lowtemp.html
=> C3 graphs, bootstrap style

freezing/web/views/api.py
=> lat lon lon lat

freezing/web/views/api.py
=> Fix track breaking

freezing/web/templates/index.html, pyproject.toml
=> Fix hour vs hours on home page

freezing/web/templates/base.html, freezing/web/views/general.py, leaderboards/decasleaze.yml
=> decasleazeboard

freezing/web/templates/people/show.html, freezing/web/templates/pointless/pointlesskids.html, freezing/web/templates/user/rides.html, freezing/web/views/general.py, leaderboards/decasleaze.yml, leaderboards/hashtag.yml
My rides page broken by reformatting.
Resolves #367
=> fix my rides and things

freezing/web/templates/base.html, freezing/web/templates/people/ridedays.html, freezing/web/views/people.py
The page assumed you were a contender if you have ridden N-1 days. That is not true, you are only a contender if you have ridden N-1 days and not ridden today.
=> Fix every day riders

.github/workflows/build-latest.yml, README.md, freezing/web/templates/base.html
Relates to https://github.com/freezingsaddles/freezing-shared/issues/3
=> Fix default branch name to main

freezing/web/templates/people/show.html
=> amended daily ride totals

freezing/web/templates/people/show.html, freezing/web/views/people.py
=> fix view person

freezing/web/static/css/styles.css, freezing/web/templates/explore/distance_by_lowtemp.html, freezing/web/templates/leaderboard/indiv.html, freezing/web/templates/leaderboard/indiv_text.html, freezing/web/templates/leaderboard/team.html, freezing/web/templates/leaderboard/team_text.html, freezing/web/views/api.py, freezing/web/views/chartdata.py, freezing/web/views/shared_sql.py
=> Migrate core leaderboards to c3

freezing/web/templates/explore/team_weekly_points.html, freezing/web/templates/user/rides.html, freezing/web/views/chartdata.py, freezing/web/views/general.py
My points by day/week, team points by week.
Relates to #416
=> Knock out three more google charts

freezing/web/static/css/styles.css, freezing/web/templates/explore/team_cumul.html, freezing/web/templates/leaderboard/indiv_text.html, freezing/web/templates/leaderboard/team_text.html, freezing/web/views/chartdata.py, freezing/web/views/leaderboard.py
Highlight your row in the individual/team text leaderboards. Migrate team cumulative charts to C3.
=> C3 cumulative charts and highlight self

freezing/web/templates/explore/indiv_elev_dist.html, freezing/web/templates/leaderboard/team_various.html, freezing/web/views/chartdata.py
=> Show team name in bubble tooltips

freezing/web/views/leaderboard.py, freezing/web/views/shared_sql.py
=> fix with friends

README.md
=> minor:  fix spelling of hans's last name

freezing/web/static/css/styles.css, freezing/web/templates/index.html, freezing/web/views/general.py, leaderboards/pointlesskids.yml
Logged-in riders see a box with their stats.
=> Add your stats box to home page

freezing/web/views/general.py
At seven pm things start to go wrong..
=> timezone horror pt 1

freezing/web/views/general.py, freezing/web/views/photos.py
=> Sort photos by global time

freezing/web/data.py, freezing/web/views/chartdata.py
=> More sqlalchemy deprecations

README.md
This is mostly a dummy PR to trigger a deploy via CI.
=> Clarify documentation on SQL session

freezing/web/templates/index.html, freezing/web/templates/people/ridedays.html, freezing/web/views/general.py, freezing/web/views/people.py
=> Count every day riders
