bafs/views/chartdata.py

The labels for the new charts were incorrect (only min value and athlete name were correct). The ancilary non-min values (like location, date, duration) selected by the previous queries didn't actually grab the values corresponding to the min value.  For example, my personal min temperature of 12.9 was attributed to Jan 4, although that temperature actually occurred on Jan 8.  Now the dates, durations, and locations of the scores shown in the mouse-hover labels are correct.

Fix queries

---

requirements.txt

Remediates:
[CVE-2018-1000656](https://nvd.nist.gov/vuln/detail/CVE-2018-1000656)
moderate severity
Vulnerable versions: < 0.12.3
Patched version: 0.12.3
The Pallets Project flask version Before 0.12.3 contains a CWE-20: Improper Input Validation vulnerability in flask that can result in Large amount of memory usage possibly leading to denial of service. This attack appear to be exploitable via Attacker provides JSON data in incorrect encoding. This vulnerability appears to have been fixed in 0.12.3.
[CVE-2018-17175](https://nvd.nist.gov/vuln/detail/CVE-2018-17175)
high severity
Vulnerable versions: < 2.15.1
Patched version: 2.15.1
In the marshmallow library before 2.15.1 and 3.x before 3.0.0b9 for Python, the schema "only" option treats an empty list as implying no "only" option, which …

Fix security issues with flask and marshmallow

---

freezing/web/data.py
freezing/web/serialize.py
freezing/web/templates/login.html
freezing/web/templates/login_results.html
freezing/web/views/general.py
requirements.txt

Updates to authorization endpoints and the functions they call to deal with
storing both access tokens, refresh tokens, and the time they expire.
This requires freezing-model 0.3.0+ to get updated models that support the
athlete.refresh_token and athlete.expires_at models.
Update scopes to those currently supported by Strava

Fixes for strava auth changes #62

---

freezing/web/templates/base.html
freezing/web/templates/pointless/kidsathlon.html
freezing/web/views/people.py
freezing/web/views/pointless.py
leaderboards/opmdays.yml

@obscurerichard can you check this? None of the generic yml leaderboards are working for me locally so it's not tested, but the change was really simple (adding an actual OPM snow day instead of Jan 26th)

We have a snow day

---

freezing/web/views/general.py

```
[2019-01-14 13:55:21 +0000] [9] [ERROR] Error handling request /authorization?state=&code=7f1f632befb6954108115c196fd803909fbf9d50&scope=read,activity:read_all,profile:read_all,read_all
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/freezing/web/views/general.py", line 231, in authorization
athlete_model=athlete_model,
File "/usr/local/lib/python3.6/dist-packages/freezing/web/data.py", line 206, in register_athlete_team
raise MultipleTeamsError(matches)
freezing.web.exc.MultipleTeamsError: [<Club id=496122 name='Team 12 - The Freezing Dozen' resource_state=2>, <Club id=496919 name='Team never2cold' resource_state=2>]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

Fix double exceptions

---

freezing/web/templates/base.html
freezing/web/templates/index.html

This adds credits and a link to the GitHub repository on each page by
adding a paragraph after the footer block. The credits on index.html
are removed.

Adds credits footer to each page. Closes #115

---

Dockerfile
resources/docker/sources.list

This works with Alpine linux just fine. The `Dockerfile` is much simpler this way.
These changes also make the app run as a non-root-user named `freezing` for better security.
This shrinks the image by almost 2/3:
```
$ docker images | grep freezing-web
local/freezing-web             latest              268e4449c3c1        41 minutes ago      121MB
freezingsaddles/freezing-web   latest              426eef8bfff0        28 hours ago        331MB
```

Simplify Dockerfile - alpine base, run as freezing

---

freezing/web/templates/base.html
freezing/web/templates/pointless/daily_variance.html
freezing/web/views/pointless.py

Created a new leaderboard for the least daily variance prize. I still don't know how to create a view in prod, but here's the SQL:
`create or replace view variance_by_day as 
select 
ds.athlete_id,
sum(case when ds.points>10 then 1 else 0 end) ride_days,
sum(distance) total_miles,
var_pop(case when ds.dow=1 then ds.distance end) sun_var_pop,
var_pop(case when ds.dow=2 then ds.distance end) mon_var_pop,
var_pop(case when ds.dow=3 then ds.distance end) tue_var_pop,
var_pop(case when ds.dow=4 then ds.distance end) wed_var_pop,
var_pop(case when ds.dow=5 then ds.distance end) thu_var_pop,
var_pop(case when ds.dow=6 then ds.distance end) fri_var_pop,
var_pop(case when ds.dow=7 then ds.distance end) sat_var_pop
from (select *, dayofweek(ride_date) as dow from daily_scores) ds group by …

daily variance leaderboard 

---

freezing/web/templates/pointless/hashtag.html

The code that does the case-insensitive search is at freezing/web/views/pointless.py .  `where R.name like concat('%', '#', :hashtag, '%')` is case insensitive.

it is not case sensitive

---

freezing/web/templates/people/ridedays.html
freezing/web/views/people.py

Stop the ride-days clock at the end of the competition. Adjust ordering of one-day-short riders to put contenders above non-contenders. Resolves #118.

end of ride days

---

docker-compose.yml
freezing/web/utils/genericboard.py
requirements.txt
setup.py

I tested this locally on a Windows system running Docker Desktop 3.0, using the docker-compose.yml changes here, plus a SQL dump file  freezing-2020-11-19.sql and an .env file derived from the production system from 2020. This fixes the regressions that made it into master, and reconciles the changes that had to be made with freezing-model too.
The docker image I built from this locally has been pushed to Docker Hub and deployed to production.

Fix Yaml loader and get working docker-compose localdev environment working

---

freezing/web/templates/base.html
leaderboards/hashtag.yml
setup.py

* Bicycle Bingo leaderboard
* For singlespeed this year, the number of rides doesn't matter. It's simply most miles wins. Delete the column that's tracking number of rides.

Pointless fixes

---

.github/workflows/build-docker.yml
.github/workflows/build-latest.yml
.github/workflows/build-tag.yml
.github/workflows/build.yml
.github/workflows/lint.yml
Dockerfile

Add Docker build

---

freezing/web/templates/authorize.html

Fixes [https://github.com/freezingsaddles/freezing-web/security/code-scanning/2](https://github.com/freezingsaddles/freezing-web/security/code-scanning/2)
To fix the problem, we need to ensure that the value retrieved from the `#public-scope` input element is properly sanitized before being used to set `window.location.href`. One way to achieve this is by using a safe method to encode the URL, ensuring that any potentially harmful characters are escaped.
We can use the `encodeURIComponent` function to encode the URL values before setting `window.location.href`. This function encodes special characters, making it safe to use in a URL context.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 2: DOM text reinterpreted as HTML

---

.gitignore
freezing/web/__init__.py
freezing/web/config.py

This was a weird one, it snuck in after we did some Flask upgrades at
some point.
```
$ APP_SETTINGS=development.cfg freezing-server
Traceback (most recent call last):
File "/Users/rbulling/Documents/src/freezingsaddles/freezing-web/.venv/bin/freezing-server", line 5, in <module>
from freezing.web.runserver import main
File "/Users/rbulling/Documents/src/freezingsaddles/freezing-web/freezing/web/__init__.py", line 8, in <module>
app = Flask(__name__, static_folder="static", static_url_path="/")
File "/Users/rbulling/Documents/src/freezingsaddles/freezing-web/.venv/lib/python3.10/site-packages/flask/app.py", line 239, in __init__
super().__init__(
File "/Users/rbulling/Documents/src/freezingsaddles/freezing-web/.venv/lib/python3.10/site-packages/flask/sansio/app.py", line 304, in __init__ …
```

Fix Flask startup error from lack of instance_path

---

freezing/web/templates/index.html
freezing/web/views/api.py

I find the current heatmap to be too blurred. Making it less blurred, it becomes too spotty because of the sampling frequency along the paths. Polylines are much cleaner (here, colour-coded by team), but don't as clearly highlight activity. Upsampling the spotty paths results in too much geometry for the heatmap to handle performantly.
Current heatmap:
Less-blurred heatmap:
Polylines instead:

Consider polylines instead of heatmap

---

freezing/web/templates/base.html
leaderboards/hashtag.yml

closes #386 
I also made a few decisions re: copy (calling the prize "Capital Bikeshsare" and using "CaBi" as the preferred contraction) and added the hashtag to the "Active Pointless Prizes" dropdown. Unsure if this was part of the request.

Add CaBi hashtag leaderboard entry

---

leaderboards/hashtag.yml

As @merlinorg  notes this leaderboard should be ranked by mileage, not rides. Tested locally:
* #386 
* #396

Rank by miles for #cabi leaderboard

---

README.md

In #360  we fixed the project to use `pyproject.toml` but did not update all the docs to match. There's no more `requirements.txt` and the documentation on integrating with `freezing-model` needed updating too. This resolves those issues.
* https://github.com/freezingsaddles/freezing-shared/issues/5
* https://github.com/freezingsaddles/freezing-web/pull/360

Eliminate requirements.txt in docs

---

freezing/web/templates/explore/indiv_elev_dist.html
freezing/web/templates/explore/riders_by_lowtemp.html
freezing/web/templates/explore/team_cumul.html
freezing/web/templates/explore/team_weekly_points.html
freezing/web/templates/leaderboard/indiv.html
freezing/web/templates/leaderboard/team.html
freezing/web/templates/user/rides.html
freezing/web/views/chartdata.py

Fix embarrassing spinner

---

freezing/web/static/css/styles.css
freezing/web/templates/alt_scoring/indiv_freeze.html
freezing/web/templates/alt_scoring/indiv_hains.html
freezing/web/templates/alt_scoring/indiv_sleaze.html
freezing/web/templates/alt_scoring/team_hains.html
freezing/web/templates/alt_scoring/team_sleaze.html
freezing/web/templates/base.html
freezing/web/templates/index.html
freezing/web/templates/leaderboard/indiv_various.html
freezing/web/templates/leaderboard/team_various.html
freezing/web/templates/tribes/leaderboard.html
freezing/web/templates/tribes/my.html
freezing/web/views/alt_scoring.py
freezing/web/views/leaderboard.py
freezing/web/views/shared_sql.py

Add freeze points with friends

---

freezing/web/config.py

Let the browser cache static files for 24 hours

---

freezing/web/templates/authorization_success.html
freezing/web/templates/leaderboard/indiv_text.html
freezing/web/templates/leaderboard/team_text.html
freezing/web/templates/people/friends.html
freezing/web/utils/genericboard.py
freezing/web/views/alt_scoring.py
freezing/web/views/api.py
freezing/web/views/chartdata.py
freezing/web/views/general.py
freezing/web/views/leaderboard.py
freezing/web/views/people.py
freezing/web/views/pointless.py

Relates to #405. This passes the wget-spider.sh test.

Remove usages deprecated by sqlalchemy 2.0 from freezing-web

---

freezing/web/templates/authorize.html

Folks often ask about missing rides because their profiles are private. We should just default this way so all rides show up.

Default to including private rides

---

freezing/web/config.py
freezing/web/data.py
freezing/web/utils/auth.py
freezing/web/views/general.py

This rolls back athlete creation during login if the athlete is not valid, rather than leaving partial athletes committed. Best review with ignore whitespace. Can't test this locally because Strava auth to local is unlikely to be permitted.
Also bump session duration to the length of the competition.
Resolves #439

Move responsibility for transaction commit up closer to where it belongs

---

freezing/web/templates/base.html
freezing/web/views/pointless.py
leaderboards/arlington-ccw.yml
leaderboards/arlington-cw.yml
leaderboards/arlington.yml

Promote Loopy for Arlington to main
